### ISSUE TITLE
Reactor crashes with StackOverflow.

### ISSUE THREAD

**Issue by lakerd** [reactor/reactor#409]
```
[2014-12-13 16:19:41.252] [ERROR] ringBuffer-65                 reactor.core.Reactor                                              null java.lang.StackOverflowError: null
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2276)
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2248)
	at java.util.Calendar.setTimeInMillis(Calendar.java:1140)
	at java.util.Calendar.setTime(Calendar.java:1106)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:955)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:948)
	at java.text.DateFormat.format(DateFormat.java:336)
	at ch.qos.logback.core.util.CachingDateFormatter.format(CachingDateFormatter.java:49)
	at ch.qos.logback.classic.pattern.DateConverter.convert(DateConverter.java:63)
	at ch.qos.logback.classic.pattern.DateConverter.convert(DateConverter.java:23)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:37)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:119)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:168)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:60)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:134)
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:188)
	at ch.qos.logback.core.FileAppender.writeOut(FileAppender.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:148)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:103)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:280)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:267)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:449)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:403)
	at ch.qos.logback.classic.Logger.log(Logger.java:803)
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:133)
	at com.xxx.xxxx.xxxx.xxxxxx.UpdateConsumer.accept(UpdateConsumer.java:89)
	at com.xxx.xxxx.xxxx.xxxxxx.UpdateConsumer.accept(UpdateConsumer.java:44)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:73)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
	at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:84)
```
How to reproduce:

Create a Consumer and throw a ClassCastException in the accept() method.

What actually happens is that ArgumentConverterConsumerInvoker will try to guess the argument type of the Consumer. If that fails with a ClassCastException it will proceed further with the guessing. However when the ClassCastException is thrown via the accept() method it will keep calling it until the reactor crashes.

https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/event/routing/ArgumentConvertingConsumerInvoker.java#L72-L79

**Comment by smaldini** [comment]
Should be fixed in latest snapshot as Observable/EventBus invokation mech has changed.

**Comment by tuhinkanti** [comment]
We see a similar line by line error when using 2.0.8 release.
`java.lang.StackOverflowError: null
    at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312)
    at java.util.Calendar.setTimeInMillis(Calendar.java:1804)
    at java.util.Calendar.setTime(Calendar.java:1770)
    at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
    at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
    at java.text.DateFormat.format(DateFormat.java:345)
    at ch.qos.logback.core.util.CachingDateFormatter.format(CachingDateFormatter.java:48)
    at ch.qos.logback.classic.pattern.DateConverter.convert(DateConverter.java:61)
    at ch.qos.logback.classic.pattern.DateConverter.convert(DateConverter.java:1)
    at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:36)
    at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:114)
    at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
    at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:1)
    at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:130)
    at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:187)
    at ch.qos.logback.core.FileAppender.writeOut(FileAppender.java:256)
    at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
    at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:228)
    at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
    at ch.qos.logback.classic.Logger.error(Logger.java:538)
    at reactor.bus.EventBus$2.accept(EventBus.java:233)
    at reactor.bus.EventBus$2.accept(EventBus.java:224)
    at reactor.bus.EventBus$3.accept(EventBus.java:317)
    at reactor.bus.EventBus$3.accept(EventBus.java:310)
    at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:72)
    at reactor.bus.EventBus$1.accept(EventBus.java:211)
    at reactor.bus.EventBus$1.accept(EventBus.java:207)
    at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:77)
    at reactor.bus.EventBus.accept(EventBus.java:591)
    at reactor.bus.EventBus.accept(EventBus.java:63)
    at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160)
    at reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:74)
    at reactor.core.dispatch.ThreadPoolExecutorDispatcher$1.rejectedExecution(ThreadPoolExecutorDispatcher.java:70)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at reactor.core.dispatch.ThreadPoolExecutorDispatcher.execute(ThreadPoolExecutorDispatcher.java:156)
    at reactor.core.dispatch.MultiThreadDispatcher.scheduleLater(MultiThreadDispatcher.java:54)
    at reactor.core.dispatch.AbstractLifecycleDispatcher.dispatch(AbstractLifecycleDispatcher.java:128)
    at reactor.bus.EventBus.notify(EventBus.java:368)
    at com.salesforce.dva.synthetics.executor.Publisher.publishTestCaseCompletion(Publisher.java:37)
    at `
