### ISSUE TITLE
Deadlock when exiting application that uses buffer() with timeout

### ISSUE THREAD

**Issue by oiavorskyi** [reactor/reactor#441]
Code below produces deadlock in RC1:

```
@SpringBootApplication
public class SmStreamsApplication implements CommandLineRunner {

    static {
        Environment.initialize();
    }

    public static void main( String[] args ) {
        SpringApplication.run(SmStreamsApplication.class, args);
    }

    @Override
    public void run( String... args ) throws Exception {
        CountDownLatch latch = new CountDownLatch(1);

        Broadcaster<String> inputStream = Broadcaster.create();

        inputStream
                .dispatchOn(Environment.cachedDispatcher())
                .buffer(2, 100, MILLISECONDS)
                .map(s -> "Hello " + s)
                .observe(s -> latch.countDown())
                .consume(s -> System.out.printf("[Thread=%s] %s\n", currentThread().getName(), s));

        inputStream.onNext("World");

        if ( !latch.await(1, SECONDS) ) {
            System.out.println("Timed out");
        }
    }

}
```

I have tried to play with values for timeout and waiting for latch and looks like that problem only happens when particular ratio exists. For example, with timeout values in buffer() less than 100ms application finishes successfully, with values between 100 and 899 it hangs and then from 900 and higher it works again. Changing wait time for latch to 2 seconds brings upper boundary of deadlock from 899 to 1899 for the timeout value.

I don't think it is numbers magic so most likely there is some kind of granularity on the timer level involved which creates deadlock. The issue is reproducible 100% of a time.

Funny enough, I just decided to play tonight with new Reactor Streams implementation in RC1 and hit this weird defect which depends on exact combination of timeout values. I should probably buy a lottery ticket :)

**Comment by smaldini** [comment]
Unfortunate innit! Can you paste the stacktrace to just see where the deadlocks is detected ? Or you are meaning that latch is never counted down in some cases ?

**Comment by oiavorskyi** [comment]
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.0-b70 mixed mode):

"DestroyJavaVM" #16 prio=5 os_prio=31 tid=0x00007f9b08cea000 nid=0x1303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"simple-hash-wheel-timer-3" #15 daemon prio=5 os_prio=31 tid=0x00007f9b0950e000 nid=0x5303 waiting on condition [0x0000000121662000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at reactor.fn.timer.SimpleHashWheelTimer$1.run(SimpleHashWheelTimer.java:118)
	at java.lang.Thread.run(Thread.java:744)

"pool-1-thread-1" #14 prio=5 os_prio=31 tid=0x00007f9b0951d800 nid=0x5103 waiting on condition [0x0000000120f33000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000798ddd0c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

"hash-wheel-timer-2" #13 daemon prio=5 os_prio=31 tid=0x00007f9b08cfc000 nid=0x4f03 waiting on condition [0x0000000120941000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at reactor.fn.timer.HashWheelTimer$SleepWait.waitUntil(HashWheelTimer.java:507)
	at reactor.fn.timer.HashWheelTimer$2.run(HashWheelTimer.java:145)
	at java.lang.Thread.run(Thread.java:744)

"dispatcherGroup-1" #12 daemon prio=5 os_prio=31 tid=0x00007f9b08cfb000 nid=0x4d03 waiting on condition [0x0000000120738000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000798ddd6f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at reactor.jarjar.com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
	at reactor.core.dispatch.wait.AgileWaitingStrategy.waitFor(AgileWaitingStrategy.java:47)
	at reactor.jarjar.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
	at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

"Monitor Ctrl-Break" #9 daemon prio=5 os_prio=31 tid=0x00007f9b088dc000 nid=0x4b03 runnable [0x000000011fc0c000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000079627b468> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x000000079627b468> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:88)
	at java.lang.Thread.run(Thread.java:744)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007f9b0981b000 nid=0x4703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f9b08827000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f9b08826800 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f9b0905a800 nid=0x4103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f9b08825800 nid=0x400f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f9b0a006800 nid=0x2d03 in Object.wait() [0x000000011da32000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
	- locked <0x0000000740096bb0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f9b0a005800 nid=0x2b03 in Object.wait() [0x000000011d92f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x0000000740098910> (a java.lang.ref.Reference$Lock)

"VM Thread" os_prio=31 tid=0x00007f9b09047000 nid=0x2903 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f9b08809000 nid=0x2103 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f9b08809800 nid=0x2303 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f9b0880a800 nid=0x2503 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f9b0880b000 nid=0x2703 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007f9b0981b800 nid=0x4903 waiting on condition 

JNI global references: 330

Heap
 PSYoungGen      total 55808K, used 15949K [0x0000000795580000, 0x0000000799300000, 0x00000007c0000000)
  eden space 53248K, 25% used [0x0000000795580000,0x000000079629a9f0,0x0000000798980000)
  from space 2560K, 98% used [0x0000000798d80000,0x0000000798ff8d40,0x0000000799000000)
  to   space 4096K, 0% used [0x0000000798980000,0x0000000798980000,0x0000000798d80000)
 ParOldGen       total 129536K, used 7727K [0x0000000740000000, 0x0000000747e80000, 0x0000000795580000)
  object space 129536K, 5% used [0x0000000740000000,0x000000074078be00,0x0000000747e80000)
 Metaspace       used 19360K, capacity 19628K, committed 19968K, reserved 1067008K
  class space    used 2342K, capacity 2435K, committed 2560K, reserved 1048576K

**Comment by oiavorskyi** [comment]
This is the output of app. The process does not make any progress after that until killed.

2015-03-04 08:11:59.988  INFO 2582 --- [           main] o.o.smstreams.SmStreamsApplication       : Starting SmStreamsApplication on mba.local with PID 2582 (/Users/oiavorskyi/IdeaProjects/sm-streams/target/classes started by oiavorskyi in /Users/oiavorskyi/IdeaProjects/sm-streams)
2015-03-04 08:12:00.048  INFO 2582 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1fc2b765: startup date [Wed Mar 04 08:12:00 CST 2015]; root of context hierarchy
2015-03-04 08:12:01.962  INFO 2582 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-03-04 08:12:01.969  INFO 2582 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
[Thread=dispatcherGroup-1] Hello [World]
2015-03-04 08:12:02.658  INFO 2582 --- [           main] o.o.smstreams.SmStreamsApplication       : Started SmStreamsApplication in 3.067 seconds (JVM running for 3.466)

**Comment by smaldini** [comment]
I need to have a closer look at that before GA, bear with me. It seems to me its not a deadlock but an infinite wait from the main as it stands (the buffer never got received). A quick confirmation of that would be to add log('after-buffer') right after buffer operation and look for any onNext logs.

**Comment by oiavorskyi** [comment]
Looks like buffering actually happens. Output after suggested changes:
2015-03-25 12:38:06.877  INFO 1714 --- [           main] o.o.smstreams.SmStreamsApplication       : Starting SmStreamsApplication on mba.local with PID 1714 (/Users/oiavorskyi/IdeaProjects/sm-streams/target/classes started by oiavorskyi in /Users/oiavorskyi/IdeaProjects/sm-streams)
2015-03-25 12:38:06.970  INFO 1714 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@87f383f: startup date [Wed Mar 25 12:38:06 EDT 2015]; root of context hierarchy
2015-03-25 12:38:08.806  INFO 1714 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-03-25 12:38:08.819  INFO 1714 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2015-03-25 12:38:09.117  INFO 1714 --- [           main] after-buffer                             : subscribe: MapAction-{{dispatcher=immediate, max-capacity=infinite}}
2015-03-25 12:38:09.122  INFO 1714 --- [           main] after-buffer                             : onSubscribe: {push}
2015-03-25 12:38:09.124  INFO 1714 --- [spatcherGroup-1] after-buffer                             : request: 9223372036854775807
2015-03-25 12:38:09.462  INFO 1714 --- [spatcherGroup-1] after-buffer                             : onNext: [World]
[Thread=dispatcherGroup-1] Hello [World]
2015-03-25 12:38:09.466  INFO 1714 --- [           main] o.o.smstreams.SmStreamsApplication       : Started SmStreamsApplication in 3.011 seconds (JVM running for 3.411)
