### ISSUE TITLE
Netty ByteBuf leak from NettyNetChannelInboundHandler

### ISSUE THREAD

**Issue by sshcherbakov** [reactor/reactor#442]
The Netty ResourceLeakDetector reports ByteBuf leaks on GC

````
2015-02-19 17:12:40,314 1.1.0.RELEASE ERROR reactor-tcp-io-5 util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected.
Recent access records: 2
#2:
        io.netty.buffer.AdvancedLeakAwareByteBuf.nioBuffer(AdvancedLeakAwareByteBuf.java:667)
        reactor.io.net.impl.netty.NettyNetChannelInboundHandler.passToConnection(NettyNetChannelInboundHandler.java:204)
        reactor.io.net.impl.netty.NettyNetChannelInboundHandler.channelRead(NettyNetChannelInboundHandler.java:146)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:744)
#1:
        io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:589)
        io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:744)
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:259)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107)
        io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:744)


---------------------------------------------------------------------------
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to com.gs.collections.impl.list.mutable.FastList
        at reactor.util.PartitionedReferencePile.get(PartitionedReferencePile.java:64)
        at reactor.event.dispatch.AbstractMultiThreadDispatcher.allocateRecursiveTask(AbstractMultiThreadDispatcher.java:45)
        at reactor.event.dispatch.AbstractLifecycleDispatcher.dispatch(AbstractLifecycleDispatcher.java:131)
        at reactor.core.Reactor.notify(Reactor.java:242)
        at reactor.core.Reactor.notify(Reactor.java:249)
        at reactor.core.Reactor.notify(Reactor.java:57)
        at reactor.core.action.Action.notifyValue(Action.java:77)
        at reactor.core.action.CollectAction.doFlush(CollectAction.java:47)
        at reactor.core.action.CollectAction.flush(CollectAction.java:55)
        at reactor.core.action.FlushableAction.doAccept(FlushableAction.java:36)
        at reactor.core.action.Action.accept(Action.java:52)
        at reactor.core.action.Action.accept(Action.java:32)
        at reactor.event.routing.ArgumentConvertingConsumerInvoker.invoke(ArgumentConvertingConsumerInvoker.java:73)
        at reactor.event.routing.ConsumerFilteringEventRouter.route(ConsumerFilteringEventRouter.java:78)
        at reactor.event.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:64)
        at reactor.event.dispatch.AbstractMultiThreadDispatcher$MultiThreadTask.run(AbstractMultiThreadDispatcher.java:55)
        at reactor.event.dispatch.WorkQueueDispatcher$3.onEvent(WorkQueueDispatcher.java:89)
        at reactor.event.dispatch.WorkQueueDispatcher$3.onEvent(WorkQueueDispatcher.java:86)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)




18:13:42.394 ERROR [reactor-tcp-io-69] i.n.u.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected.
Recent access records: 3
#3:
        io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:691)
        io.netty.channel.ChannelOutboundBuffer.nioBuffers(ChannelOutboundBuffer.java:384)
        io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:254)
        io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:716)
        io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:303)
        io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:685)
        io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1118)
        io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
        io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:693)
        io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681)
        io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716)
        io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:954)
        io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:243)
        reactor.io.net.impl.netty.NettyChannelStream.write(NettyChannelStream.java:97)
        reactor.io.net.impl.netty.NettyChannelStream.write(NettyChannelStream.java:92)
        reactor.io.net.ChannelStream.write(ChannelStream.java:195)
        reactor.io.net.ChannelStream$WriteConsumer.accept(ChannelStream.java:235)
        reactor.rx.action.terminal.ConsumerAction.doNext(ConsumerAction.java:77)
        reactor.rx.action.Action.onNext(Action.java:192)
        reactor.rx.subscription.PushSubscription.onNext(PushSubscription.java:105)
        reactor.rx.stream.SingleValueStream$1.request(SingleValueStream.java:70)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:68)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:35)
        reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:151)
        reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:89)
        io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:745)
#2:
        io.netty.buffer.AdvancedLeakAwareByteBuf.nioBufferCount(AdvancedLeakAwareByteBuf.java:661)
        io.netty.channel.ChannelOutboundBuffer.nioBuffers(ChannelOutboundBuffer.java:372)
        io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:254)
        io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:716)
        io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:303)
        io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:685)
        io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1118)
        io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
        io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:693)
        io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681)
        io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716)
        io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:954)
        io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:243)
        reactor.io.net.impl.netty.NettyChannelStream.write(NettyChannelStream.java:97)
        reactor.io.net.impl.netty.NettyChannelStream.write(NettyChannelStream.java:92)
        reactor.io.net.ChannelStream.write(ChannelStream.java:195)
        reactor.io.net.ChannelStream$WriteConsumer.accept(ChannelStream.java:235)
        reactor.rx.action.terminal.ConsumerAction.doNext(ConsumerAction.java:77)
        reactor.rx.action.Action.onNext(Action.java:192)
        reactor.rx.subscription.PushSubscription.onNext(PushSubscription.java:105)
        reactor.rx.stream.SingleValueStream$1.request(SingleValueStream.java:70)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:68)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:35)
        reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:151)
        reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:89)
        io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:745)
#1:
        io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:577)
        reactor.io.net.impl.netty.NettyChannelStream.write(NettyChannelStream.java:91)
        reactor.io.net.ChannelStream.write(ChannelStream.java:195)
        reactor.io.net.ChannelStream$WriteConsumer.accept(ChannelStream.java:235)
        reactor.rx.action.terminal.ConsumerAction.doNext(ConsumerAction.java:77)
        reactor.rx.action.Action.onNext(Action.java:192)
        reactor.rx.subscription.PushSubscription.onNext(PushSubscription.java:105)
        reactor.rx.stream.SingleValueStream$1.request(SingleValueStream.java:70)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:68)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:35)
        reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:151)
        reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:89)
        io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:745)
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:259)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
        io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:83)
        reactor.io.net.impl.netty.NettyChannelStream.write(NettyChannelStream.java:90)
        reactor.io.net.ChannelStream.write(ChannelStream.java:195)
        reactor.io.net.ChannelStream$WriteConsumer.accept(ChannelStream.java:235)
        reactor.rx.action.terminal.ConsumerAction.doNext(ConsumerAction.java:77)
        reactor.rx.action.Action.onNext(Action.java:192)
        reactor.rx.subscription.PushSubscription.onNext(PushSubscription.java:105)
        reactor.rx.stream.SingleValueStream$1.request(SingleValueStream.java:70)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:68)
        reactor.rx.subscription.PushSubscription.accept(PushSubscription.java:35)
        reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:151)
        reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:89)
        io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        java.lang.Thread.run(Thread.java:745)
18:13:45.673 WARN  [reactor-tcp-io-69] i.n.c.n.NioEventLoop - Unexpected exception in the selector loop.
java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.ReferenceCountUtil
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:288) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:589) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:718) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:309) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:519) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
````

**Comment by smaldini** [comment]
Hmmm there are a few errors on the same stack ! will investigate if its related. First will try to address the release() issue, but the MultiThreadDispatcher exception is quite weird (and also the NoClassDefFoundError), @jbrisbin I might need you for these 2 ones.

**Comment by jbrisbin** [comment]
These stacktraces are from two different versions of Reactor. Is that what's being illustrated? We tried to make sure all package names between 1.1 and 2.0 were orthogonal so that the two could co-exist. 

It's likely that the leaks are a side effect of the underlying errors. I've seen that message when buffers aren't handled entirely on the Netty EventLoop threads (which would probably be the case if an error occurred and caused a dispatch out of the Netty EventLoop thread prematurely).

**Comment by sshcherbakov** [comment]
The first stack trace is from a Spring XD environment with a module referencing Reactor 2.0.0.RC1 explicitly. Spring XD DIRT itself depends on Reactor 1.1, so it may have come to collision.
The second stack trace is from a unit test that uses 2.0.0.RC1 too.
Which path in the traces is from Reactor 1.1?

**Comment by jbrisbin** [comment]
Looks like there's a mishmash of versions. The dead giveaway is the references to `reactor.core.Reactor`, which doesn't exist in 2.0 (it was renamed `EventBus`).

Other references to the `reactor.io.net.impl` are from Reactor 2.0.

**Comment by sshcherbakov** [comment]
The ClassCastException appears in the logs shorty after Netty's warning.
It might have come from SXD's internals.

**Comment by jbrisbin** [comment]
I looked at the code for `PartitionedReferencePile` and that shouldn't happen at all. There's no code in that class that sets an `Object[]` for that key. The fact that it's showing up at all is strange.

Is there a codec in place that reads all data from Netty's `ByteBuf` before passing an object downstream? I have seen this error before when this is not the case.

**Comment by sshcherbakov** [comment]
Yes, there is a custom codec.
The codec doesn't use Netty classes and references `reactor.io.buffer.Buffer` only.
The stack trace with `PartitionedReferencePile ` is not reported by Netty.
The leak is detected on the other paths, I should probably remove the misleading stack trace.

**Comment by jbrisbin** [comment]
Does the codec read all possible data from the `Buffer` before dispatching onto a non-Netty thread?

**Comment by sshcherbakov** [comment]
The Codec is based (almost completely) on a [FrameCodec](https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/io/codec/FrameCodec.java)
The main purpose was to make FrameCodec be capable to delegate to SnappyCodec.
So it reads all data up to delimiter and passes that to the delegate [at this place](https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/io/codec/FrameCodec.java#L83).
(sorry, don't have a link to real code)

**Comment by smaldini** [comment]
I need to also look at the Pooled Buffer in use now in server/client creation, I changed that to align with Norman best practices when it comes to Netty use but I may have missed impl details like making sure a buffer is released after use in deserialization/serialization phases.

**Comment by smaldini** [comment]
I mean this
```java
		.childOption(ChannelOption.AUTO_READ, sslOptions != null)
```

**Comment by sshcherbakov** [comment]
The Netty leak warning tend to appear around same time as some errors are thrown in end consumer.
Don't you think that the release() might be missed [here](https://github.com/reactor/reactor/blob/master/reactor-net/src/main/java/reactor/io/net/impl/netty/NettyNetChannelInboundHandler.java#L151) (the place pointed out by the first stack trace)?

**Comment by smaldini** [comment]
This is related to the read part which might be fine, but the write part I believe since there are write calls in the stack. So maybe around https://github.com/reactor/reactor/blob/master/reactor-net/src/main/java/reactor/io/net/impl/netty/NettyChannelStream.java#L90

**Comment by smaldini** [comment]
Does the client closes connection by itself or the server does it ? BTW if you could enable reactor.io.net in DEBUG mode and gives us some packet info that would be awesome.

**Comment by sshcherbakov** [comment]
On the client side (pure SI tcp-outbound-adapter) I see frequently "Read Exception: Connection reset".
According to the server logs, the server-side connection on().close() is called frequently (once in a second).
Which part closes connection is not yet clear to me. I would expect it to be the client.

**Comment by smaldini** [comment]
Is that one fixed ?

**Comment by smaldini** [comment]
I still need to make sure I can avoid leak even if the client / server is failing, the close is now properly handled in theory but there might be a short circuit due to the fast fail nature of error signals that by pass the buffer.release(). I will evaluate that in a new test before stating this issue fixed.

**Comment by smaldini** [comment]
Can't reproduce for now
