### ISSUE TITLE
Netty keeps trying to write to closed channel

### ISSUE THREAD

**Issue by jvalkeal** [reactor/reactor#450]
I believe stream should be cancelled automatically if client goes away which currently doesn't happen.

With a simple test:
```
	@Test
	public void foo2() throws Exception {
		Broadcaster<String> broadcaster = Broadcaster.<String> create(Environment.sharedDispatcher());
		Stream<List<String>> tail = broadcaster.buffer(10).broadcast().keepAlive();

		ListCodec codec = new ListCodec();
		reactor.io.net.http.HttpServer<List<String>, List<String>> httpServer = NetStreams.httpServer(server -> server
				.codec(codec).listen(8080).dispatcher(Environment.sharedDispatcher()));

		httpServer.get("/data", (request) -> {

			return tail.map(x -> x);
		});

		httpServer.start().awaitSuccess();

		System.out.println("XXXX broadcast start");
		for (int i = 0; i < 1000000; i++) {
			Thread.sleep(100);
			System.out.println("XXXX i " + i);
			broadcaster.onNext(i + "\n");
		}
		System.out.println("XXXX broadcast end");
		Thread.sleep(60000);
	}
```

I open a client using curl and close it almost immediately:
```
$ curl http://localhost:8080/data
0
1
2
3
4
5
6
7
8
9
<ctrl-c>
```

server logs:
```
XXXX i 48
XXXX i 49
10:51:24,142 ERROR reactor-tcp-io-8 netty.NettyChannelStream [reactor-tcp-io-8] - 
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:503)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:285)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:716)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:303)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:685)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1118)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:197)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:961)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
10:51:24,147 ERROR reactor-tcp-io-8 reactor-environment [reactor-tcp-io-8] - 
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:503)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:285)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:716)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:303)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:685)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1118)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:197)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:961)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
10:51:24,149 ERROR reactor-tcp-io-8 reactor-environment [reactor-tcp-io-8] - 
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:503)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:285)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:716)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:303)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:685)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1118)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:197)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:961)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
XXXX i 50
XXXX i 51
XXXX i 52
XXXX i 53
XXXX i 54
XXXX i 55
XXXX i 56
XXXX i 57
XXXX i 58
XXXX i 59
10:51:25,143 ERROR reactor-tcp-io-8 netty.NettyChannelStream [reactor-tcp-io-8] - 
java.nio.channels.ClosedChannelException
10:51:25,143 ERROR reactor-tcp-io-8 reactor-environment [reactor-tcp-io-8] - 
java.nio.channels.ClosedChannelException
XXXX i 60
XXXX i 61
XXXX i 62
XXXX i 63
XXXX i 64
XXXX i 65
XXXX i 66
XXXX i 67
XXXX i 68
XXXX i 69
10:51:26,145 ERROR reactor-tcp-io-8 netty.NettyChannelStream [reactor-tcp-io-8] - 
java.nio.channels.ClosedChannelException
10:51:26,146 ERROR reactor-tcp-io-8 reactor-environment [reactor-tcp-io-8] - 
java.nio.channels.ClosedChannelException
XXXX i 70
XXXX i 71
XXXX i 72
```

ListCodec was just something dummy I used for testing:

```
public class ListCodec extends Codec<Buffer, List<String>, List<String>> {

	@Override
	public Buffer apply(List<String> t) {
		StringBuffer buf = new StringBuffer();
		if (t.isEmpty()) {
			buf.append("END\n");
		} else {
			for (String n : t) {
				buf.append(n);
			}
		}
		String data = buf.toString();
		return new Buffer().append(data.getBytes()).flip();
	}

	@Override
	public Function<Buffer, List<String>> decoder(Consumer<List<String>> next) {
		return null;
	}

}
```

**Comment by smaldini** [comment]
Fixed in https://github.com/reactor/reactor/commit/e3b6be6fbd3b98e5e4ae1b04e760677a9e168e55
