### ISSUE TITLE
RingBufferWorkProcessor stuck

### ISSUE THREAD

**Issue by christian-laakmann** [reactor/reactor#496]
Hi all,

due to #479 we moved most of our implementation over to RingBufferWorkProcesser, which perfect for most of our use cases.

However, we have a problem doing this:

```
RingBufferWorkProcessor<Integer> processor = RingBufferWorkProcessor.create("test", 8192);

      Stream<Integer> stream = Streams.wrap(processor);

      CountDownLatch latch = new CountDownLatch(4);

      Consumer<Void> completeConsumer = c -> {
        latch.countDown();
        System.out.println(Thread.currentThread().getName() + " completed");
      };

      stream.buffer(1000).consume(e -> {}, t -> {}, completeConsumer);
      stream.buffer(1000).consume(e -> {}, t -> {}, completeConsumer);
      stream.buffer(1000).consume(e -> {}, t -> {}, completeConsumer);
      stream.buffer(1000).consume(e -> {}, t -> {}, completeConsumer);

      processor.onNext(1);
      processor.onComplete();

      if (!latch.await(30, TimeUnit.SECONDS)) {
        System.err.println("not completed");
        throw new RuntimeException("not completed");
      }
```

We create 4 worker threads but have fewer values to be send over the processor. From time to time, not all worker threads will complete correctly (i.e. latch.await(...) fails).

Here's a thread dump taken at a breakpoint in the if-clause:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.novomind.iport.process.StreamTest.processorTest(StreamTest.java:53)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:483)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.executeTestMethod(JUnit4TestRunnerDecorator.java:131)
	  at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:71)
	  at mockit.integration.junit4.internal.MockFrameworkMethod.invokeExplosively(MockFrameworkMethod.java:42)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:483)
	  at mockit.internal.util.MethodReflection.invokeWithCheckedThrows(MethodReflection.java:112)
	  at mockit.internal.mockups.MockMethodBridge.callMock(MockMethodBridge.java:85)
	  at mockit.internal.mockups.MockMethodBridge.invoke(MockMethodBridge.java:44)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:483)
	  at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)

"test-18@1259" prio=5 tid=0x20 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at reactor.jarjar.com.lmax.disruptor.LiteBlockingWaitStrategy.waitFor(LiteBlockingWaitStrategy.java:56)
	  at reactor.jarjar.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
	  at reactor.core.processor.RingBufferWorkProcessor$WorkSignalProcessor.replay(RingBufferWorkProcessor.java:802)
	  at reactor.core.processor.RingBufferWorkProcessor$WorkSignalProcessor.run(RingBufferWorkProcessor.java:726)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"test-20@1260" prio=5 tid=0x22 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at reactor.jarjar.com.lmax.disruptor.LiteBlockingWaitStrategy.waitFor(LiteBlockingWaitStrategy.java:56)
	  at reactor.jarjar.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
	  at reactor.core.processor.RingBufferWorkProcessor$WorkSignalProcessor.run(RingBufferWorkProcessor.java:760)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"test-17@1257" prio=5 tid=0x1f nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at reactor.jarjar.com.lmax.disruptor.LiteBlockingWaitStrategy.waitFor(LiteBlockingWaitStrategy.java:56)
	  at reactor.jarjar.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
	  at reactor.core.processor.RingBufferWorkProcessor$WorkSignalProcessor.run(RingBufferWorkProcessor.java:760)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"Finalizer@1406" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler@1407" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)

"Attach Listener@745" daemon prio=5 tid=0x5 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Signal Dispatcher@1405" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
```

Any ideas?

**Comment by smaldini** [comment]
For this you can use buffer with timeout buffer(size, time, unit) to force pending value to release.

**Comment by smaldini** [comment]
Although I would encourage to use buffer before the work processor after a Broadcaster or another  processor, better to distribute batches together IMO.

**Comment by christian-laakmann** [comment]
Regarding comment 1) In our production code, the value is processed due to the onComplete call and those workers return without any problems. Usually some threads that didn't process any values are stuck.

Regarding 2) I didn't understand you fully, I think. Do you mean a pipline like this:

```
stream = Streams.wrap(processor1)
             .map(...)
             .processor(processor2)
             .batch(...);

stream.consume();
stream.consume();
...
```

**Comment by christian-laakmann** [comment]
We fixed those issues by moving to back pressure enabled streams instead of hot streams. 

I guess it's just a matter of knowing and understanding your tools ☺

Thanks again for the awesome library.

**Comment by udayabaski** [comment]
Hi,
   I have the same problem. 
private static RingBufferWorkProcessor<TestEvent> processor = RingBufferWorkProcessor.<TestEvent> create("test", 128);
processor.subscribe(testSubscriber);

@Component
public class TestSubscriber implements Subscriber<testEvent> {
    private static Log log = new Log(TestSubscriber.class);

    @Override
    public void onSubscribe(final Subscription s) {
        if (s != null) {
            s.request(Long.MAX_VALUE);
        }
    }

    @Override
    public void onNext(final TestEvent testEvent) {
        if (testEvent == null) {
            return;
        }
        if ((testEvent.getBroadcastType() != null) && testEvent.getBroadcastType().isTrue()) {
            ReactorResources.publish(testEvent.getType().name(), testEvent);
        } else {
            ReactorResources.publish(testEvent.getName(), testEvent);
        }
    }

    @Override
    public void onError(final Throwable t) {
        if (t != null) {
            log.error(t.getMessage());
        }
    }

    @Override
    public void onComplete() {
        log.info("TestSubscriber is done.");
    }
}

Posting event,

while(it.hasNext()) {
  processor.onNext(it.next());
}

It stucks after processing few hundred messages.

"workQueueDispatcher-3" daemon prio=5 tid=42 TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at reactor.jarjar.com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:136)
	at reactor.jarjar.com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:105)
	at reactor.jarjar.com.lmax.disruptor.RingBuffer.next(RingBuffer.java:246)
	at reactor.core.dispatch.WorkQueueDispatcher.allocateTask(WorkQueueDispatcher.java:172)
	at reactor.core.dispatch.MultiThreadDispatcher.allocateRecursiveTask(MultiThreadDispatcher.java:59)
	at reactor.core.dispatch.AbstractLifecycleDispatcher.dispatch(AbstractLifecycleDispatcher.java:116)
	at reactor.bus.EventBus.notify(EventBus.java:368)
	   Local Variable: reactor.bus.Event#6
