### ISSUE TITLE
OSGi java.lang.NoClassDefFoundError: sun/misc/Unsafe

### ISSUE THREAD

**Issue by jmnarloch** [reactor/reactor#553]
Hi,

I'm trying to run Reactor (2.0.5-RELEASE) in Apache Felix (which is generally OSGi runtime - in my case embedded part of Go Continuous Delivery server), but experience this error:

```
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at reactor.jarjar.com.lmax.disruptor.util.Util$1.run(Util.java:102)
	at reactor.jarjar.com.lmax.disruptor.util.Util$1.run(Util.java:99)
	at java.security.AccessController.doPrivileged(Native Method)
	at reactor.jarjar.com.lmax.disruptor.util.Util.<clinit>(Util.java:108)
	at reactor.jarjar.com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
	at reactor.fn.timer.HashWheelTimer.<init>(HashWheelTimer.java:110)
	at reactor.fn.timer.HashWheelTimer.<init>(HashWheelTimer.java:91)
	at reactor.fn.timer.HashWheelTimer.<init>(HashWheelTimer.java:67)
	at reactor.Environment.getTimer(Environment.java:792)
	at reactor.Environment.timer(Environment.java:184)
	at reactor.rx.Streams.period(Streams.java:405)
```

Have you ever encountered similar problem?

**Comment by ifesdjeen** [comment]
We run it with Karaf and Felix, all is smooth.

**Comment by CodingFabian** [comment]
Newer Versions of reactor do this differently, but you still need to add sun.misc.unsafe to your bootclasspath / framework extras. 
I am going to provide a patch to reactor which initializes unsafe safely

**Comment by CodingFabian** [comment]
Just doublechecked. it turns out in current 2.0.x head all calls to unsafe are guarded, so you should not encounter this anymore.

**Comment by smaldini** [comment]
Yes Master and from 2.1 onwards will support Unsafe-less environments with a small hit in perfs (we are roughly speaking lets say about 15M/s messages per sec on a simple async pipeline SpSc to 14M/s...).

**Comment by CodingFabian** [comment]
@smaldini you missed the chance to call that class NoFunsafe :)
