### ISSUE TITLE
ClassCastException in CachableRegistration

### ISSUE THREAD

**Issue by morca** [reactor/reactor#558]
Sometimes in a stress test we get following Exception:

```
java.lang.ClassCastException: de.abas.mw.core.connection.events.EventKey cannot be cast to java.lang.Void
    at reactor.bus.registry.CachableRegistration$1.matches(CachableRegistration.java:28)
    at reactor.bus.registry.CachingRegistry.select(CachingRegistry.java:117)
    at reactor.bus.EventBus.accept(EventBus.java:591)
    at reactor.bus.EventBus.accept(EventBus.java:63)
    at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160)
    at reactor.core.dispatch.SingleThreadDispatcher$SingleThreadTask.run(SingleThreadDispatcher.java:79)
    at reactor.core.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:156)
    at reactor.core.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:153)
    at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ifesdjeen** [comment]
Could you provide more detail for that? Or particular steps to reproduce?

**Comment by morca** [comment]
I don't know how to reproduce it.
It happens occasionally.
Our EventKey is a simple class extended from Object.

**Comment by smaldini** [comment]
Any code sample ? Version used , JVM too would be helpful :)

**Comment by morca** [comment]
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

reactor version: 2.0.5.RELEASE

may be we send events after cancelling the registration.

**Comment by dguggemos** [comment]
We also encounter the described exception. Seems to be a problem to match a cancelled registration. It can be reproduced like this (Reactor 2.0.6.RELEASE):
```java
CachableRegistration r = new CachableRegistration(Selectors.$("test"), new Object(), ()->{});
r.cancel();
r.getSelector().matches("test");
```
