### ISSUE TITLE
Operator chaining is not stack-safe

### ISSUE THREAD

**Issue by pakoito** [reactor/reactor#655]
I was running some tests over Mono to see the performance of long chained operations that yielded that operators like `Mono#map` and `Mono#flatMap` are not stack-safe.

```java
Range.create(0, 5000)
  .toList()
  .fold(Mono.just(0), { mono, x ->
    mono.map { x }
  }).block()
  .shouldBe(5000)
```

Yields a StackOverflow error:

```
java.lang.StackOverflowError
        at reactor.core.publisher.MonoJust.$jacocoInit(MonoJust.java)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
        ...
```

I have seen that these operators are supposed to support operator fusion, which is not triggering here for some reason.

My environment is Kotlin 1.3, Java 7, with JUnit5 and kotlintest as the test runners.

**Comment by pakoito** [comment]
This should probably go into reactor-core
